[project]
name = "dev-shared"
dynamic = ["version"]
description = "dev-shared"
classifiers = [
    "Private :: Do Not Upload",
]
requires-python = ">=3.10"

dependencies = [
    "pytest",
    "pytest-mock",
    "pytest-cov",
    "poethepoet",
    "setuptools-scm",
    "ruff",
    "mypy",
    "ty>=0.0.1a32",
]

[tool.ruff]
line-length = 79
